New "Asking for feedback" page (closes #38)
LandRegistry/hmlr-design-system pull request #85
Opened 2023-01-05 09:23 UTC by ahosgood

2023-01-05 10:26 UTC, AndyPorter commented on src/patterns/asking-for-feedback/index.md.njk
> +The laws that apply to pages we build ourselves equally apply to third-party ones. For example, we are responsible for following data protection laws and the Equality Act 2010. .
i think we can make the slime clearer - and remove the additional full stop.

"The laws that apply to pages we build ourselves equally apply to third-party ones. For example, we are responsible for following data protection laws and the Equality Act 2010. ."


I suggest saying...
"The laws that apply to pages we build ourselves apply equally to those we choose to include from third parties. We, as the operator of the service, are responsible for those third party pages (or sub services) meeting the laws.  For example data protection laws and the Equality Act 2010."

"If outsourcing data collection and processing, you will probably need a lawyer to help fully understand the data protection laws in the UK and assess the potential partners’ privacy and security procedures."

2023-01-05 10:34 UTC, AndyPorter commented on src/patterns/asking-for-feedback/index.md.njk
> +Does a service have to do it? (Welsh – think this lives n the Welsh guidance)
remove the following content from this page

Does a service have to do it? (Welsh – think this lives n the Welsh guidance)
Dunno - to write. Ask a lawyer, ask them early on - e.g., early in Alpha."

2023-01-05 10:39 UTC, AndyPorter requested changes
consider my comment on line 66 about making the point on our responsibility for third parties clearer.  But at least remove the additional full stop on the current line 66

remove lines 142 to 145 - comment on line 142 indicates what content to remove

2023-01-06 10:24 UTC, accessibilitydesign approved these changes

2023-01-06 15:52 UTC, ahosgood commented on src/patterns/asking-for-feedback/index.md.njk
> +The laws that apply to feedback pages we code ourselves apply equally to those we choose to include from third parties. As the operator of the service, we are responsible for those third parties comp
Not sure I understand what this paragraph is trying to say. If we use a third party tool (e.g. Google Analytics) then it isn't our responsibility to ensure their compliance.

2023-01-06 15:58 UTC, ahosgood commented on src/patterns/asking-for-feedback/index.md.njk
> +## Accessibility and inclusivity
Is this somewhat a duplication of what is in the Accessibility section of the Design System?

2023-10-27 11:54 UTC, closed without merging